# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'M80ImageMerger' do
  pod 'PureLayout'
	pod 'SVProgressHUD'
	pod 'Toast'
  pod 'Fabric'
  pod 'Crashlytics'
#  pod 'MixboxCocoaImageHashing', '~> 0.2.150'
  pod 'CocoaImageHashing', :git => 'https://github.com/ameingast/cocoaimagehashing.git'
end
